version: "3"
services:
  eve-movies-db:
    container_name: eve-movies-db
    image: mongo
    ports:
      - "27018:27017"

  eve-movies-core:
    container_name: eve-movies-core
    restart: always
    build: ../evemovies-core
    ports:
      - "3001:3001"
    depends_on:
      - eve-movies-db

  eve-movies-web:
    container_name: eve-movies-web
    restart: always
    build: ../evemovies-web
    ports:
      - "3000:3000"
    depends_on:
      - eve-movies-core

  # eve-moviles-mobile:
  #   container_name: eve-movies-mobile
  #   restart: always
  #   build: ../evemovies-mobile
  #   depends_on:
  #     - eve-movies-core
